### ISSUE TITLE
bench.pl installed to `@INC`

### ISSUE THREAD

**Issue by kentfredric** [rjbs/String-Formatter#2]
ExtUtils::MakeMaker due to hysterical raisins, installs *.pl into `@INC`. 

You can demonstrate this trivially by performing the following anywhere it is installed: 

```
perl -e 'require q[String/bench.pl] '
```
>```
I like to eat apples and bananas.I like to eat apples and bananas.I like to eat apples and bananas.Benchmark: timing 100000 iterations of dlc, perl, rjbs...
       dlc:  1 wallclock secs ( 1.40 usr +  0.00 sys =  1.40 CPU) @ 71428.57/s (n=100000)
      perl:  0 wallclock secs ( 0.00 usr +  0.00 sys =  0.00 CPU)
            (warning: too few iterations for a reliable count)
      rjbs:  3 wallclock secs ( 3.13 usr +  0.00 sys =  3.13 CPU) @ 31948.88/s (n=100000)
```

**Comment by rjbs** [comment]
Thanks, fixed in git.
